In [2]:
import numpy as np
#creating vectors
v1=np.array([1,2,3])
v2=np.array([4,5,6])

In [3]:
print(v1)
print(v2)

[1 2 3]
[4 5 6]


In [4]:
v_add=v1+v2
v_sub=v1-v2

In [5]:
print(v_add,v_sub)

[5 7 9] [-3 -3 -3]


In [6]:
scalar=2
scaled=v1*scalar
print(scaled)

[2 4 6]


In [7]:
dot_prod=np.dot(v1,v2)

In [8]:
print(dot_prod)

32


In [9]:
magnitude=np.linalg.norm(v1)

In [10]:
print(magnitude)

3.7416573867739413


In [11]:
A=np.array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [12]:
B=np.array([[7,8,9],[10,11,12],[13,14,15]])
print(B)

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [14]:
C=np.array([[1,2,3],[4,5,6]])
add=A+C
sub=A-C
print(add)
print(sub)

[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]


In [20]:
mult=A*C
print(mult)
transpose=A.T

[[ 1  4  9]
 [16 25 36]]


In [22]:
A=np.array([[2,3],[4,-1]])
b=np.array([5,3])
x=np.linalg.solve(A,b)
print(x)

[1. 1.]


In [27]:
A=np.array([[2,1],[1,2]])
e_val,e_vec=np.linalg.eig(A)
print("eiganvalue:",e_val)
print("eiganvector", e_vec)

eiganvalue: [3. 1.]
eiganvector [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [30]:
A=np.array([[4,7],[2,6]])
A_inv=np.linalg.inv(A)
print(A)
print(A_inv)

[[4 7]
 [2 6]]
[[ 0.6 -0.7]
 [-0.2  0.4]]


In [32]:
identity=np.dot(A,A_inv)
print(identity)

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


In [ ]:
A=np.array([[1,2],[3,4],[5,6]])
U,sigma,Vt=np.linalg.svd(A)